services:
  qdrant:
    image: qdrant/qdrant:v1.18.0
    container_name: qdrant_local
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    restart: unless-stopped

  mongo:
    image: mongo:8.0
    container_name: mongo_local
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    restart: unless-stopped